#!/usr/bin/env bash
[[ "$1" == "pkg-update" ]] && yay -Qe | awk '{print $1}' > packages.yay && exit

mkdir -p ~/.config/kitty
ln -sf $(pwd)/kitty.conf ~/.config/kitty/kitty.conf
ln -sf $(pwd)/nvim ~/.config
mkdir -p ~/.config/Code\ -\ OSS/User
ln -sf $(pwd)/code.json ~/.config/Code\ -\ OSS/User/settings.json
ln -sf $(pwd)/zshrc ~/.zshrc
mkdir -p ~/.local/bin
ln -sf $(pwd)/chrono ~/.local/bin
ln -sf $(pwd)/emoji ~/.local/bin

