# Disable mouse acceleration
xinput --set-prop 'Logitech G403 Prodigy Gaming Mouse' 'libinput Accel Profile Enabled' 0, 1 &
# Configure 2 monitor, resolution, position and refresh rate
xrandr --output DisplayPort-1 --mode 1920x1080 --rate 144 --output DVI-D-0 --mode 1366x768 --pos 1920x670
# Configure my input layouts
# setxkbmap -model pc104 -layout us,us,us -variant ,alt-intl,colemak -option caps:swapescape -option grp:menu_toggle & # FOR PROGRAMMING
setxkbmap -model pc104 -layout us -variant alt-intl & # FOR GAMING
# Start digital vibrance for games
vibrantLinux --hidden &
# Enhance typing speed
xset r rate 300 50 &
# Start conky, so i never forget the keybindings
#conky -c $HOME/.config/conky/doom-one-01.conkyrc &
# Start desktop compositor
#picom & # xcompmgr or picom
# Start sxhkd to handle keybindings
#sxhkd &
# Start clipman so i can take prints to the clipboard
xfce4-clipman &
# Set a nice wallpaper
loadwall &
# Start redshift for blue light filter
#redshift -l -22.90:-47.06 &
# Start dunst for notifications
dunst &
# Start unclutter to hide mouse
unclutter &
# Start nm-applet to configure network (proxy/vpn/dns/wifi)
nm-applet &
# Start music daemon
mpd &
# Start screen locker
xss-lock --transfer-sleep-lock -- slock &
# Load xresources
xrdb ~/.config/x11/xresources
# Enable xdg-desktop-portal-gtk 
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
# Start fcitx
fcitx -d &
# Start kdeconnect-indicator
kdeconnect-indicator &
# Start transmission-daemon
# transmission-daemon &
# Start i3 window manager
exec gnome-session


