name = "João Gabriel Sabatini"
downloads-dir = "~/.cache/himalaya"

[outlook]
default = true
default-page-size = 25

email = "jgabrielsabatini@outlook.com"

signature = """
Regards,
João Gabriel Sabatini
"""

imap-host = "outlook.office365.com"
imap-port = 993
imap-login = "jgabrielsabatini@outlook.com"
imap-passwd-cmd = "pass microsoft"

smtp-host = "smtp.office365.com"
smtp-port = 587
smtp-starttls = true
smtp-login = "jgabrielsabatini@outlook.com"
smtp-passwd-cmd = "pass microsoft"

