#!/usr/bin/env bash
[ "$1" == "gen" ] && date +"%s" > ~/.cache/fap && exit

DATE_OLD=$(cat ~/.cache/fap)
DATE_NOW=$(date +"%s")
DATE_DIFF=$(echo "$DATE_NOW - $DATE_OLD" | bc)

MONTHS=$(echo "$DATE_DIFF/60/60/24/30" | bc)
DATE_DIFF=$(echo "$DATE_DIFF - ($MONTHS * 30 * 24 * 60 * 60)" | bc)

DAYS=$(echo "$DATE_DIFF/60/60/24" | bc)
DATE_DIFF=$(echo "$DATE_DIFF - ($DAYS * 24 * 60 * 60)" | bc)

HOURS=$(echo "$DATE_DIFF/60/60" | bc)
DATE_DIFF=$(echo "$DATE_DIFF - ($HOURS * 60 * 60)" | bc)

MINUTES=$(echo "$DATE_DIFF/60" | bc)
DATE_DIFF=$(echo "$DATE_DIFF - ($MINUTES * 60)" | bc)

SECONDS=$DATE_DIFF

PERCENTAGE=$(echo "($DAYS/90)*100" | bc -l | awk -F. '{print $1}')

NEXT_CHECKPOINT=$(echo "24-$HOURS" | bc)

COMPLETED_MSG=$(echo "Completed: $MONTHS months $DAYS days $HOURS hours $MINUTES minutes $SECONDS seconds.")
NEXT_CHECKPOINT_MSG=$(echo "$NEXT_CHECKPOINT hours to next checkpoint.")

[ "$1" == "notify" ] && notify-send "$NEXT_CHECKPOINT_MSG" "$COMPLETED_MSG" && exit
[ "$1" == "simple" ] && echo "$DAYS/$MONTHS/$YEARS $HOURS:$MINUTES:$SECONDS" && exit

echo "Initial date: $(date -d @$DATE_OLD)."
echo "Now date: $(date)."
echo "$COMPLETED_MSG"
echo "Challenge duration: 90 days."
echo "Challenge progress: $DAYS/90 days."
echo "Challenge percentage: $PERCENTAGE%."
echo "$NEXT_CHECKPOINT_MSG"
